--==============================
-- Complaint functions
--==============================

--- Returns whether a mail can be reported as spam. Returns nil for messages from Game Masters or friends, as well as for messages generated by the game itself (Auction House mail, mails from NPCs, etc).
---@param mailID number Index of a mail in the player's inbox (between 1 and GetInboxNumItems() )
---@return any complain 1 if the mail can be reported as spam; otherwise nil
function CanComplainInboxItem(mailID) end

--- Reports a mail message as spam
---@param mailID number Index of a message in the player's inbox (between 1 and GetInboxNumItems() )
function ComplainInboxItem(mailID) end
